/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.AFASystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.EmployeeDirectory;
import Business.UserAccount.UserAccount;

/**
 *
 * @author sujayghodke
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    JPanel userProcessContainer;
    private AFASystem system;
    public RegisterJPanel(JPanel userProcessContainer,AFASystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer =userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        BtnCreat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNa = new javax.swing.JTextField();

        setBackground(new java.awt.Color(185, 153, 103));

        jLabel1.setText("Customer Name:");

        jLabel2.setText("Password:");

        BtnCreat.setText("Create");
        BtnCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreatActionPerformed(evt);
            }
        });

        jLabel3.setText("User Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtNa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(BtnCreat)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(BtnCreat)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreatActionPerformed
        // TODO add your handling code here:
        System.out.println(system);
        String name = txtNa.getText();
        EmployeeDirectory ed = system.getEmployeeDirectory();
        System.out.println(ed);
        Employee employee = null;
        String userName =txtName.getText();
        String password = txtPassword.getText();
        boolean exist=false;
        if(!txtNa.getText().equals(txtName.getText())){
            JOptionPane.showMessageDialog(null, "UserAccount and Name should be the same!");
        }
        else if(txtNa.getText().equals("")|| userName.equals("")
                    ||password.equals("")){
                 JOptionPane.showMessageDialog(null, "one or more fields are empty.");
                 return;
            }else{
            for(UserAccount userAccount: system.getUserAccountDirectory().getUserAccountList()){
                if(userAccount.getUsername().equals(userName)){
                    JOptionPane.showMessageDialog(null, "Customer already exist!");
                    exist=true;
                    break;
                }
            }
            if(exist==false){
            system.getUserAccountDirectory().createUserAccount(userName, password, employee, new CustomerRole());
            DB4OUtil.getInstance().storeSystem(system);
            JOptionPane.showMessageDialog(null, "You are registered successfully!");
            
            txtNa.setText("");
            txtName.setText("");
            txtPassword.setText("");
            }
        }  
        
        
    }//GEN-LAST:event_BtnCreatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNa;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
